window.TM_SEED = {
  categories: ["Loza", "Cubiertos", "Vasos de cerveza", "Vasos / jugos", "Copas"],
  interpretedDates: {
    previous: "2026-08-11T12:00:00-04:00",
    current: "2026-08-24T12:00:00-04:00"
  },
  items: [
    ["TM-LOZ-001","Loza","Tazas","Taza de café pequeña",12,12],
    ["TM-LOZ-002","Loza","Tazas","Taza de café mediana",11,11],
    ["TM-LOZ-003","Loza","Tazas","Taza de café grande",8,8],
    ["TM-LOZ-004","Loza","Tazas","Taza de té",13,13],
    ["TM-LOZ-005","Loza","Platos de café","Plato de café pequeño",12,13],
    ["TM-LOZ-006","Loza","Platos de café","Plato de café mediano",5,5],
    ["TM-LOZ-007","Loza","Platos de café","Plato de café grande",9,9],
    ["TM-LOZ-008","Loza","Platos de café","Plato de té",13,13],
    ["TM-LOZ-009","Loza","Mantequilleros","Mantequillero cuadrado",12,12],
    ["TM-LOZ-010","Loza","Mantequilleros","Mantequillero redondo",3,3],
    ["TM-LOZ-011","Loza","Otros","Cenicero",3,3],
    ["TM-LOZ-012","Loza","Teteras","Tetera blanca",2,2],
    ["TM-LOZ-013","Loza","Platos","Plato de pan",87,87],
    ["TM-LOZ-014","Loza","Platos","Plato azul de postre",10,10],
    ["TM-LOZ-015","Loza","Platos","Plato negro de postre",2,2],
    ["TM-LOZ-016","Loza","Platos","Plato naranjo",1,1],
    ["TM-LOZ-017","Loza","Platos","Plato cuadrado blanco",5,5,false,"Cantidad interpretada como 5; ya confirmada."],

    ["TM-CUB-001","Cubiertos","Tenedores","Tenedor de postre",19,19],
    ["TM-CUB-002","Cubiertos","Cucharas","Cuchara de café pequeña",23,23],
    ["TM-CUB-003","Cubiertos","Cucharas","Cuchara mediana de café",30,33],
    ["TM-CUB-004","Cubiertos","Cucharas","Cuchara larga",7,7],
    ["TM-CUB-005","Cubiertos","Cucharas","Cuchara de sopa",20,21],
    ["TM-CUB-006","Cubiertos","Tenedores","Tenedor de madera",4,4],
    ["TM-CUB-007","Cubiertos","Cuchillos","Cuchillo de madera",9,9],
    ["TM-CUB-008","Cubiertos","Cuchillos","Cuchillo de mesa",97,96],
    ["TM-CUB-009","Cubiertos","Tenedores","Tenedor de mesa",97,97],

    ["TM-VAS-001","Vasos de cerveza","Marca","Vaso Peroni",5,5],
    ["TM-VAS-002","Vasos de cerveza","Marca","Vaso Erdinger pequeño",9,9],
    ["TM-VAS-003","Vasos de cerveza","Marca","Vaso Clausthaler",5,5],
    ["TM-VAS-004","Vasos de cerveza","Marca","Vaso Gulden Draak",2,2],
    ["TM-VAS-005","Vasos de cerveza","Marca","Vaso Shop Kross",12,12],
    ["TM-VAS-006","Vasos de cerveza","Marca","Vaso Helles Lagerbier",5,5],
    ["TM-VAS-007","Vasos de cerveza","Marca","Vaso Paulaner",5,5],
    ["TM-VAS-008","Vasos de cerveza","Marca","Vaso Schlappeseppel",3,3,false,"Nombre manuscrito normalizado; editable."],
    ["TM-VAS-009","Vasos de cerveza","Marca","Vaso Schöfferhofer",3,3],
    ["TM-VAS-010","Vasos de cerveza","Marca","Vaso Urweisse",2,2],
    ["TM-VAS-011","Vasos de cerveza","Marca","Vaso Erdinger grande",9,9],
    ["TM-VAS-012","Vasos de cerveza","Marca","Vaso Liefmans",6,6],
    ["TM-VAS-013","Vasos de cerveza","Marca","Vaso Jägermeister cuadrado",4,4],
    ["TM-VAS-014","Vasos de cerveza","Marca","Vaso Jägermeister redondo",1,1],
    ["TM-VAS-015","Vasos de cerveza","Marca","Vaso Flensburger",4,4],

    ["TM-BEB-001","Vasos / jugos","Bebidas","Vaso bebida grande",11,11],
    ["TM-BEB-002","Vasos / jugos","Bebidas","Vaso bebida pequeño",15,15],
    ["TM-BEB-003","Vasos / jugos","Bebidas","Vaso Feldi",9,9,true,"Nombre manuscrito poco claro; confirmar nombre interno."],
    ["TM-BEB-004","Vasos / jugos","Jugos","Vaso de jugo",25,25],
    ["TM-BEB-005","Vasos / jugos","Helados","Vaso café helado",6,6],
    ["TM-BEB-006","Vasos / jugos","Helados","Copa de helado",4,4],
    ["TM-BEB-007","Vasos / jugos","Postres","Copa de tiramisú",8,8,true,"El segundo conteo no se distingue con total claridad; se conserva 8 hasta confirmar."],
    ["TM-BEB-008","Vasos / jugos","Marca","Vaso Hoegaarden",2,2,true,"En la libreta aparece una grafía aproximada; confirmar nombre interno."],

    ["TM-COP-001","Copas","Vino","Chardonnay pequeña",15,15,true,"El primer conteo parece anotado como 10+5; actual interpretado 15."],
    ["TM-COP-002","Copas","Vino","Chardonnay grande",2,2],
    ["TM-COP-003","Copas","Cócteles","Copa Aperol",6,6],
    ["TM-COP-004","Copas","Pisco","Copa larga pisco S.",5,5,true,"Nombre abreviado en la libreta; confirmar descripción interna."],
    ["TM-COP-005","Copas","Tante Marlene","Copa Tante Marlene P.",1,1,true,"Nombre abreviado en la libreta; confirmar descripción interna."],
    ["TM-COP-006","Copas","Pisco","Copa pisco sour normal",2,2],
    ["TM-COP-007","Copas","Tante Marlene","Copa grande Tante Marlene",1,1,true,"Nombre abreviado en la libreta; confirmar descripción interna."],
    ["TM-COP-008","Copas","Vino","Copa vino Paragoni",8,8,true,"Nombre manuscrito poco claro; confirmar."],
    ["TM-COP-009","Copas","Vino","Copa Casa Concha",4,4],
    ["TM-COP-010","Copas","Otros","Copa Forchette",2,2,true,"Nombre manuscrito a confirmar."],
  ].map(([id,category,subcategory,name,previous,current,needsReview=false,notes=""]) => ({
    id, category, subcategory, name, previous, current, quantity: current,
    needsReview, notes, minStock: null, location: "", active: true
  }))
};
